version: 2
updates:
  - package-ecosystem: npm
    open-pull-requests-limit: 5
    directory: /
    schedule:
      interval: weekly
      day: monday    
    groups:
      minor-and-patch:
        update-types: [minor, patch]
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
